---
- name: Update system (Ubuntu/Debian)
  when: ansible_os_family == 'Debian'
  apt:
    upgrade: yes
    autoremove: yes
    update_cache: yes

- name: Add hostnames to hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  with_items:
    - "192.168.1.1  gateway"
    - "192.168.1.10 omniumgatherum"
    - "192.168.1.11 desktop"

- name: Install extra packages (apt)
  become: yes
  package:
    state: present
    name:
      - "git"
      - "wget"
      - "gzip"
      - "unzip"
      - "iotop"
      - "ranger"
      - "ffmpeg"
      - "fail2ban"
      - "net-tools"
      - "certbot"
      - "syncthing"
      - "syslog-ng"
      - "nginx"
      - "samba"

- name: Install extra packages (pip)
  become: yes
  package:
    state: present
    name:
      - "brotli"
      - "yt-dlp"

- name: Check if volume exists
  when: item.mount is defined and item.mount.state == 'present'
  with_items: "{{ lvm_volumes }}"
  no_log: true
  stat:
    path: "/dev/{{ item.volume }}"
  register: "lvm_volume_exists"

- name: Add volume to /etc/fstab
  with_items: "{{ lvm_volume_exists.results }}"
  when: item.stat.exists | bool
  no_log: true
  lineinfile:
    path: /etc/fstab
    line: "/dev/{{ item.item.volume }} {{ item.item.mount.dest }} {{ item.item.mount.fs }} {{ item.item.mount.flags }}"

- name: Create folders for volumes
  with_items: "{{ lvm_volume_exists.results }}"
  when: item.stat.exists | bool
  no_log: true
  file:
    path: "{{ item.item.mount.dest }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Mount volume
  with_items: "{{ lvm_volume_exists.results }}"
  when: item.stat.exists | bool
  no_log: true
  mount:
    src: "/dev/{{ item.item.volume }}"
    path: "{{ item.item.mount.dest }}"
    fstype: "{{ item.item.mount.fs }}"
    state: mounted
