---
- name: Update system (Ubuntu/Debian)
  when: ansible_os_family == 'Debian'
  apt:
    upgrade: yes
    autoremove: yes
    update_cache: yes

- name: Add hostnames to hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  with_items:
    - "192.168.1.1  gateway"
    - "192.168.1.10 omniumgatherum"
    - "192.168.1.11 desktop"

- name: Install extra packages (apt)
  become: yes
  package:
    state: present
    name:
      - "git"
      - "wget"
      - "gzip"
      - "unzip"
      - "iotop"
      - "ranger"
      - "ffmpeg"
      - "fail2ban"
      - "net-tools"
      - "certbot"
      - "syncthing"
      - "syslog-ng"
      - "nginx"
      - "samba"

- name: Install extra packages (pip)
  become: yes
  package:
    state: present
    name:
      - "brotli"
      - "yt-dlp"

- name: Create folders for volumes
  with_items: "{{ lvm_volumes }}"
  no_log: true
  file:
    path: "{{ item.mount.dest }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Mount volume
  with_items: "{{ lvm_volumes }}"
  no_log: true
  mount:
    state: mounted
    src: "/dev/{{ item.volume }}"
    path: "{{ item.mount.dest }}"
    fstype: "{{ item.mount.fs }}"
    opts: "{{ item.mount.flags }}"
    dump: "0"
    passno: "2"
