---
- name: Download SHA256 sums
  get_url:
    url: "https://cdimage.ubuntu.com/ubuntu-server/{{ ubuntu_code }}/daily-live/current/SHA256SUMS"
    dest: "{{ working_dir }}"

- name: Get SHA256 sum for the {{ iso_arch }} ISO
  shell:
    cmd: "grep {{ iso_arch }} {{ working_dir }}/SHA256SUMS | cut -d' ' -f1"
  changed_when: false
  register: sha256sum

- name: Download latest Ubuntu {{ ubuntu_code }} {{ iso_arch }} ISO
  get_url:
    url: "https://cdimage.ubuntu.com/ubuntu-server/{{ ubuntu_code }}/daily-live/current/{{ ubuntu_code }}-live-server-{{ iso_arch }}.iso"
    dest: "{{ working_dir }}/{{ ubuntu_code }}-live-server-{{ iso_arch }}.iso"
    checksum: "sha256:{{ sha256sum.stdout }}"

- name: Download GPG keys
  get_url:
    url: "https://cdimage.ubuntu.com/ubuntu-server/{{ ubuntu_code }}/daily-live/current/SHA256SUMS.gpg"
    dest: "{{ working_dir }}"

- name: Check if dirmngr is running
  shell:
    cmd: pgrep dirmngr
  failed_when: false
  changed_when: false
  register: dirmngr_status

- name: Launch dirmngr if it isn't running
  shell:
    cmd: "dirmngr --daemon"
  when: dirmngr_status.rc != 0

- name: Import GPG key
  shell:
    cmd: "gpg -q --no-default-keyring --keyring '{{ working_dir }}/{{ ubuntu_gpg_key }}.keyring' --keyserver 'hkp://keyserver.ubuntu.com' --recv-keys {{ ubuntu_gpg_key }}"
    creates:
     - "{{ working_dir }}/{{ ubuntu_gpg_key }}.keyring"
     - "{{ working_dir }}/{{ ubuntu_gpg_key }}.keyring~"
  ignore_errors: yes

- name: Verify GPG key
  shell:
    cmd: "gpg -q --keyring '{{ working_dir }}/{{ ubuntu_gpg_key }}.keyring' --verify '{{ working_dir }}/SHA256SUMS.gpg' '{{ working_dir }}/SHA256SUMS' 2>/dev/null"
  ignore_errors: yes

- name: Kill dirmngr if we launched it
  shell:
    cmd: "pkill dirmngr"
  when: dirmngr_status.rc != 0
