---
- name: Create ISO directory
  file:
    path: "{{ working_dir }}/iso"
    state: directory

- name: Extract ISO
  shell:
    cmd: "xorriso -osirrox on -indev {{ working_dir }}/{{ ubuntu_code }}-live-server-{{ iso_arch }}.iso -extract / {{ working_dir }}/iso"

- name: Change ownership of extracted ISO
  file:
    path: "{{ working_dir }}/iso"
    mode: "u+w"
    recurse: yes
    follow: no

- name: Delete [BOOT]-folder, if needed
  file:
    path: "{{ working_dir }}/iso/[BOOT]"
    state: absent

- name: Enable HWE kernel
  replace:
    path: "{{ item }}"
    regexp: "/casper/(vmlinuz|initrd)"
    replace: '/casper/hwe-\1'
  with_items:
    - "{{ working_dir }}/iso/boot/grub/grub.cfg"
    - "{{ working_dir }}/iso/boot/grub/loopback.cfg"

- name: Change bootloader commandline
  replace:
    path: "{{ item }}"
    regexp: "---$"
    replace: " autoinstall   ds=nocloud\\;s=/cdrom/nocloud/  ---"
  with_items:
    - "{{ working_dir }}/iso/boot/grub/grub.cfg"
    - "{{ working_dir }}/iso/boot/grub/loopback.cfg"

- name: Create nocloud
  file:
    path: "{{ working_dir }}/iso/nocloud"
    state: directory

- name: Create meta-data
  file:
    path: "{{ working_dir }}/iso/nocloud/meta-data"
    state: touch
    modification_time: preserve
    access_time: preserve

- name: Generate user-data
  template:
    src: user-data.j2
    dest: "{{ working_dir }}/iso/nocloud/user-data"

- name: Calculate new MD5 hashes
  stat:
    path: "{{ item }}"
    checksum_algorithm: md5
  with_items:
    - "{{ working_dir }}/iso/boot/grub/grub.cfg"
    - "{{ working_dir }}/iso/boot/grub/loopback.cfg"
  register: md5sums

- name: Write new MD5 hashes (grub.cfg)
  lineinfile:
    line: "{{ md5sums.results[0].stat.checksum }}  ./boot/grub/grub.cfg"
    search_string: /boot/grub/grub.cfg
    path: "{{ working_dir }}/iso/md5sum.txt"

- name: Write new MD5 hashes (loopback.cfg)
  lineinfile:
    line: "{{ md5sums.results[1].stat.checksum }}  ./boot/grub/loopback.cfg"
    search_string: /boot/grub/loopback.cfg
    path: "{{ working_dir }}/iso/md5sum.txt"

- name: Repack the ISO
  shell:
    cmd: "cd {{ working_dir }}/iso && xorriso -as mkisofs -quiet -D -r -V ubuntu-autoinstall_{{ iso_arch }} -cache-inodes -J -l -joliet-long -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -eltorito-alt-boot -e boot/grub/efi.img -no-emul-boot -o {{ working_dir }}/ubuntu_autoinstall_{{ iso_arch }}.iso ."

- name: Clean up ISO directory
  file:
    path: "{{ working_dir }}/iso"
    state: absent

- name: Done!
  debug:
    msg: "Done! The ISO file has been generated: {{ working_dir }}/ubuntu_autoinstall_{{ iso_arch }}.iso"
