---
- name: Install Docker dependencies
  package:
    state: present
    name: "{{ docker_deps }}"

- name: Install Docker (Ubuntu)
  when: ansible_facts['distribution'] == 'Ubuntu'
  block:
    - name: Add Docker GPT key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }} {{ ansible_lsb['codename'] }} stable"
        state: present

- name: Install Docker
  package:
    state: present
    name: "{{ docker_pkgs }}"

- name: Install Docker module for Python
  pip:
    name: "docker"

- name: Ensure Docker is running and enabled
  service:
    name: docker
    state: started
    enabled: yes

- name: Create docker group
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: '{{ username }}'
    groups:
      - docker
    append: yes
